### ISSUE TITLE
Physics Interpolation Jitter

### ISSUE THREAD

**Issue by cadennabors** [ratmarrow/GoldGdt-Legacy#1]
There is slight camera jitter while the physics interpolation is on. Uncommenting
 `	head_resting_position = prev_headtrans.interpolate_with(curr_headtrans, clamp(Engine.get_physics_interpolation_fraction(), 0, 0.925)).origin
	head.global_position = head_resting_position` 
stops this from happening.

https://github.com/ratmarrow/GoldGdt/assets/78510667/370f96d1-8b2b-4bbf-953f-2e7b87a471cc

**Comment by cadennabors** [comment]
This still occurs with physics jitter fix off.

**Comment by ratmarrow** [comment]
Could you please tell me any changes you made to the character besides this? My testing project for GoldGdt doesn't seem to have any of these vertical jitters.

**Comment by cadennabors** [comment]
This occurs without any changes to the player.

**Comment by cadennabors** [comment]
https://github.com/ratmarrow/GoldGdt/assets/78510667/3e85736f-7a89-4baa-b78a-a964741c846b

This doesnt seem to happen all of the time. Only at some positions.

**Comment by cadennabors** [comment]
This is caused by using Jolt physics rather than Godot physics. Very odd, but I found a fix for whoever might need it.
```
func _process(delta):
	# Interpolate the player's resting position to the desired transform position.
	head_resting_position = prev_headtrans.interpolate_with(curr_headtrans, clamp(Engine.get_physics_interpolation_fraction(), 0, 0.925)).origin

	if (not prev_headtrans.origin.snapped(Vector3(0.001, 0.01, 0.001)).is_equal_approx(curr_headtrans.origin.snapped(Vector3(0.001, 0.01, 0.001)))
	or head.global_position.snapped(Vector3(0.001, 0.01, 0.001)) != head_resting_position.snapped(Vector3(0.001, 0.01, 0.001))):
		head.global_position = head_resting_position
```
^ Replace previous interpolation code with this

All it does is check if the position didn't change (but rounds the vertical position to a lower value), and if not then it doesnt change the head position. Still no jitter.

**Comment by ratmarrow** [comment]
> This is caused by using Jolt physics rather than Godot physics. Very odd, but I found a fix for whoever might need it.
> 
> ```
> func _process(delta):
> 	# Interpolate the player's resting position to the desired transform position.
> 	head_resting_position = prev_headtrans.interpolate_with(curr_headtrans, clamp(Engine.get_physics_interpolation_fraction(), 0, 0.925)).origin
> 
> 	if (not prev_headtrans.origin.snapped(Vector3(0.001, 0.01, 0.001)).is_equal_approx(curr_headtrans.origin.snapped(Vector3(0.001, 0.01, 0.001)))
> 	or head.global_position.snapped(Vector3(0.001, 0.01, 0.001)) != head_resting_position.snapped(Vector3(0.001, 0.01, 0.001))):
> 		head.global_position = head_resting_position
> ```
> 
> ^ Replace previous interpolation code with this
> 
> All it does is check if the position didn't change (but rounds the vertical position to a lower value), and if not then it doesnt change the head position. Still no jitter.

I did notice that the player itself is bobbing up and down when approaching the oven, so it may not _be_ the camera's fault, but rather the map collision geometry.

If that implementation fixed it for you though, I will keep it visible for people using Jolt in-case the weird clipping issue isn't fixed.

**Comment by cadennabors** [comment]
The map collision is just a static body box mesh, so the bobbing isn't caused by that. Bobbing is disabled on my version of the player, while the second clip i brought an unmodified player to test. It could be weird clipping due to Jolt but I doubt it.

**Comment by ratmarrow** [comment]
I just started tinkering with Jolt Physics and I noticed the jitter. Turns out, it's seemingly fixed by turning on Stop on Slope in the 'Pawn' CharacterBody3D?

Gonna run some further tests to weed out some potentially unwanted side effects.

**Comment by ratmarrow** [comment]
The solution is to enable Stop on Slope on the CharacterBody3D, and there seems to be no adverse side effects.
