### ISSUE TITLE
Using Jolt physics goes over max acceleration

### ISSUE THREAD

**Issue by OceanOC** [ratmarrow/GoldGdt-Legacy#3]
![image](https://github.com/ratmarrow/GoldGdt/assets/141111946/6db89596-5954-4204-b2e6-af5b5f139738)

I have used the default player parameters with Godot Jolt physics and it should be capped at 320 in/s (10 m/s) but its nearly goes to 400~500 range whenever turning left or right

This does not occur when default physics is used

**Comment by ratmarrow** [comment]
I'm confused on how that _doesn't_ happen on GodotPhysics for you because that is an intended quirk of the movement code.

**Comment by OceanOC** [comment]
Well, I am just dumb enough that I wouldn't notice. Sorry

**Comment by ratmarrow** [comment]
No worries, haha.
