### ISSUE TITLE
Low walls not being treated as stairs

### ISSUE THREAD

**Issue by elevchyt** [ratmarrow/GoldGdt-Legacy#4]
The logic for handling small stairs seems to be something that is missing from _handle_collision().
The controller seems to be getting stuck and treating even the tiniest stair like a wall.

https://github.com/ratmarrow/GoldGdt/assets/50188474/477ec993-f603-4ee5-b277-0a4a0faffda3

**Comment by ratmarrow** [comment]
Currently the character doesn't have stair detection yet. Once I wrap up what I am doing, I will get right on it.

**Comment by elevchyt** [comment]
Closing this, since it got fixed by @ratmarrow !
